var eventoraEvents = [
  {
    id: 1,
    title: "TechFest 2026",
    category: "Technology",
    date: "October 18, 2026",
    time: "10:00 AM",
    venue: "Main Auditorium",
    theme: "theme-tech",
    poster: "images/techfest.jpg",
    description: "A day of coding, innovation and technology challenges.",
    about:
      "A simple technology festival featuring coding challenges, project showcases and a tech quiz.",
  },
  {
    id: 2,
    title: "Cultural Night",
    category: "Cultural",
    date: "October 22, 2026",
    time: "6:00 PM",
    venue: "Open Air Theatre",
    theme: "theme-culture",
    poster: "images/cultural-night.jpg",
    description: "Music, dance and performances by the campus community.",
    about:
      "An evening celebrating creativity and campus culture with student performances.",
  },
  {
    id: 3,
    title: "Campus Hackathon",
    category: "Competition",
    date: "October 28, 2026",
    time: "9:00 AM",
    venue: "Innovation Lab",
    theme: "theme-code",
    poster: "images/hackathon.jpg",
    description: "Build a useful idea with your team in one exciting day.",
    about: "Form a team, choose a problem and build a working prototype.",
  },
  {
    id: 4,
    title: "Photography Walk",
    category: "Creative",
    date: "November 2, 2026",
    time: "8:00 AM",
    venue: "Campus Gate",
    theme: "theme-photo",
    poster: "images/photography.jpg",
    description: "Explore campus through your camera and creativity.",
    about: "A relaxed photography walk around campus.",
  },
  {
    id: 5,
    title: "Sports Day",
    category: "Sports",
    date: "November 8, 2026",
    time: "7:30 AM",
    venue: "University Ground",
    theme: "theme-sport",
    poster: "images/sports-day.jpg",
    description: "A fun-filled day of friendly sports and team activities.",
    about: "Take part in simple athletic and team activities.",
  },
  {
    id: 6,
    title: "Web Development Workshop",
    category: "Workshop",
    date: "November 15, 2026",
    time: "11:00 AM",
    venue: "Seminar Hall",
    theme: "theme-web",
    poster: "images/web-workshop.svg",
    description: "Learn the basics of responsive website building.",
    about: "A beginner-friendly workshop covering HTML, CSS and Bootstrap.",
  },
];
